# ビルドタイプに応じた定義
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_compile_definitions(_DEBUG)
    add_compile_options("/EHsc" "/MDd" "/Zi" "/Ob0" "/Od" "/RTC1")
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
    add_compile_definitions(NDEBUG)
    add_compile_options("/EHsc" "/MD" "/O2" "/Ob2" "/DNDEBUG")
elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    add_compile_definitions(NDEBUG)
    add_compile_options("/EHsc" "/MD" "/Zi" "/O2" "/Ob1" "/DNDEBUG")
elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
    add_compile_definitions(NDEBUG)
    add_compile_options("/EHsc" "/MD" "/O1" "/Ob1" "/DNDEBUG")
elseif(CMAKE_BUILD_TYPE STREQUAL "Develop")
    add_compile_definitions(_DEVELOP)
    add_compile_options("/EHsc" "/MD" "/Zi" "/O2" "/Ob1")
endif()